### ISSUE TITLE
Missing folder: "synthesis_scripts"

### ISSUE THREAD

**Issue by INASIC** [lucaskingjade/Motion_Synthesis_Adversarial_Learning#2]
Hi Qi Wang,

There appears to be a missing folder `/synthesis_scripts` at the root folder: `[Motion_Synthesis_Advserarial_Learning](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning)`, which is referenced by the code by its alias: `Seq_AAE_V1`.

Several piece of code depend on this folder such as `[dataset.py](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning/blob/master/datasets/dataset.py)` and `[seq_aae_new_loss.py](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning/blob/master/models/Seq_AAE/seq_aae_new_loss.py)` in their imports such as:

- `from Seq_AAE_V1.synthesis_scripts.synthesis_utils import denormalize,denormalize_vertical_position`

- `from Seq_AAE_V1.synthesis_scripts.synthesis_utils import save_seq_2_bvh`

Could you please upload this missing folder?

Many thanks,
Anthony

**Comment by lucaskingjade** [comment]
> Hi Qi Wang,
> 
> There appears to be a missing folder `/synthesis_scripts` at the root folder: `[Motion_Synthesis_Advserarial_Learning](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning)`, which is referenced by the code by its alias: `Seq_AAE_V1`.
> 
> Several piece of code depend on this folder such as `[dataset.py](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning/blob/master/datasets/dataset.py)` and `[seq_aae_new_loss.py](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning/blob/master/models/Seq_AAE/seq_aae_new_loss.py)` in their imports such as:
> 
> * `from Seq_AAE_V1.synthesis_scripts.synthesis_utils import denormalize,denormalize_vertical_position`
> * `from Seq_AAE_V1.synthesis_scripts.synthesis_utils import save_seq_2_bvh`
> 
> Could you please upload this missing folder?
> 
> Many thanks,
> Anthony

Hi Anthony,
I have upload the missing folder synthesis_script.
Thanks for telling me this.

**Comment by INASIC** [comment]
> Hi Qi Wang,
> There appears to be a missing folder /synthesis_scripts at the root folder: [Motion_Synthesis_Advserarial_Learning](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning), which is referenced by the code by its alias: Seq_AAE_V1.
> Several piece of code depend on this folder such as [dataset.py](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning/blob/master/datasets/dataset.py) and [seq_aae_new_loss.py](https://github.com/lucaskingjade/Motion_Synthesis_Adversarial_Learning/blob/master/models/Seq_AAE/seq_aae_new_loss.py) in their imports such as:
> 
> from Seq_AAE_V1.synthesis_scripts.synthesis_utils import denormalize,denormalize_vertical_position
> from Seq_AAE_V1.synthesis_scripts.synthesis_utils import save_seq_2_bvh
> 
> Could you please upload this missing folder?
> Many thanks,
> Anthony
> 
> Hi Anthony,
> I have upload the missing folder synthesis_script.
> Thanks for telling me this.

Thanks Qi!
